services:
  minio :
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data
    networks:
      - app-network
    expose:
      - 9000
    volumes:
      - ./data:/data
      - ./config:/root/.minio/

  minio-client:
    build: .
    ports:
      - 9001:9001
    restart: always
    networks:
      - app-network
volumes:
  data:
  config:


networks:
  app-network:
    name: minio-client
    driver: bridge
